[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "staticfiles"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.12.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
